### ISSUE TITLE
How to deal with code splitting ?

### ISSUE THREAD

**Issue by sessionboy** [lucasecdb/react-app-server#273]
I tried this library and it is great. 
But I have a problem with code splitting.

I use @loadable/component:

```js
import React from 'react'
import loadable from '@loadable/component'
// import OtherPage from './OtherPage'
import App from './index'

const OtherPage = loadable(() => import('./OtherPage'))

export default [
  {
    element: <App />,
    path: '/',
  },
  {
    element: <OtherPage />,
    path: '/other-page',
  },
]
```

It executes normally, but it is not server-side rendering, but client-side rendering.

It seems that until the server responds, the dynamic component OtherPage still does not render

The server's response is similar to the following result:
```js
<html>
   <head>
     <title>My App</title>      
   </head>
   <body>
      <div id="root">  </div>      
      <script src="static/js/main.js"></script>
      <script src="static/js/runtime-main.js"></script>
      <script src="static/js/vendors.js"></script>
  </body>
</html>
```

Search engines cannot capture complete html pages, making seo meaningless.
I don't know how to solve this problem☹️.

**Comment by lucasecdb** [comment]
hi @sessionboy, thanks for the feedback! 😄

I actually wanted to add code splitting by route natively to this library, but I don't know how to do so with the routes file the way it is now :-/

If you want to come up with a new route definition file that would allow us to code-split the components in them, feel free to send a PR! I was thinking if we could add a babel transform in this file to use dynamic imports to load the components, and add some extra code in the server to wait for the promises before rendering them.

**Comment by sessionboy** [comment]
@lucasecdb  
I have the same idea as you, but i haven't found a better solution. 
Now I hope to implement code splitting through [loadable-component](https://github.com/gregberge/loadable-components). 
The difficulty encountered now is the problem mentioned above, and I am working hard to solve it.
I am planning to rewrite it to implement my own loadable-component. 💪
